### ISSUE TITLE
Red usernames on attackers

### ISSUE THREAD

**Issue by erme0330033333** [smeysu/GTA5-TikTok-Integration#2]
How to remove usernames written in game red text? If the number of attackers is high, the game is almost invisible.

**Comment by MyShopJB** [comment]
the game becomes more interesting when there are many users with names, but the red color should be changed to white and having a black border of the names would be perfect

**Comment by Dennycakin** [comment]
bagaimana menambah perintah untuk memunculkan pesawat dan perintah pemain terbang.  trimakasih

**Comment by smeysu** [comment]
Color is now white
