### ISSUE TITLE
What is parameter of username npc

### ISSUE THREAD

**Issue by llawlliett** [smeysu/GTA5-TikTok-Integration#6]
Hi!, Does anyone know the username parameters webhooks in GTA5 Integration? 
because I'm trying to send a webhook in node js, if the npc spawns, the username tiktok not showing, only the npc spawns
can anyone tell me?

Thanks you

**Comment by llawlliett** [comment]
solved

**Comment by megaminerg** [comment]
Hi, i'm using Python and same problem, can you share what parameter you use ? i'm using http://127.0.0.1:6721/spawn_attackers:1 and the npc only spawn with no name thx.

**Comment by megaminerg** [comment]
For everyone who wants the username in python 😁:         data = {'username': 'Testuser123'}
        requests.post(webhook_url, data=data)

**Comment by armnew12** [comment]
hello how to solve broken npc spawn on webhook.  logs
Failed to execute command spawn_attackers. Error: The type initializer for 'SHVDN.NativeMemory' threw an exception.
